### PR TITLE
Add singularity config

### PR DESCRIPTION
**Pull request by sven1103**
Provide a singularity config, so one can run a nf-core pipeline with a `singularity` profile (`-profile singularity`).

### CODE REVIEW

**Review by apeltzer — CHANGES_REQUESTED** [review]
Not sure this is the way to go - we had something else in mind at some point maybe: https://github.com/nf-core/methylseq/blob/bb83fffeb621a316fa9194a7cf12ad9472d2b0ac/nextflow.config#L51

**Comment by apeltzer** [comment]
Might be that I missed some discussion as we didn't specify a container URI beforehand...

**Review by apeltzer — APPROVED** [review]
Better - thanks. I guess we'Ll have to update everywhere to include the singularity special URI + scope, as this is better than pulling from Docker Hub...

**Comment by sven1103** [comment]
Now that we are having Singularity container hosted on shub, it makes sense to pull them, and avoid the conversion overhead, when pulling from docker hub.

**Comment by ewels** [comment]
As this is only two lines, it might be easier to just put this in `nextflow.config`..?

Interesting idea with using the pipeline name for the singularity image, but I would prefer to do this differently. As it stands, the code now hardcodes in the singularity image path without any option to change it. It also bypasses `params.container` as used by the docker profile, which is kind of confusing. Finally, it's not linted - not sure if it's reported properly in the log too?

My intention before was to use the existing `params.container` variable and substitute in the hyphen. But that's probably also too simplistic. We may need a more complete overhaul here.

**Comment by ewels** [comment]
Moved discussion to an issue instead of a merged PR. See #47.

**Pull request merged**
