### PR TITLE
Update .gitattributes for nextflow syntax

### PR DESCRIPTION
**Pull request by ewels**
I found the reason that the GitHub bar was still saying there was a bunch of Groovy code in the repo. This change fixes that, and also adds syntax highlighting to the config files not called `nextflow.config` (those in the `config/` subdirectory).

### CODE REVIEW

**Comment by maxulysse** [comment]
Stealing that right now

**Review by maxulysse — DISMISSED** [review]

**Comment by ewels** [comment]
This is waiting on PR #19 by @apeltzer so that the tests pass..

**Comment by ewels** [comment]
Ok, so this got a little messy sorry. But I forgot to branch and pulled @apeltzer's changes from #19.

Anyway - I think that there was only one small update required there and tests are now passing for me locally. Hopefully they'll pass here too now and we can merge 🤞

**Review by maxulysse — APPROVED** [review]
I like how it's cleaner and easier to understand.

**Comment by ewels** [comment]
Thanks! Kudos goes to @apeltzer who did the vast majority of this PR. Merging..

**Pull request merged**
